// File generated by textgen.c
#include <wchar.h>
#include "dchar.h"
#include "lstring.h"
#include "dscript.h"
#include "text.h"
//
// *** BASIC TEXT / KEYWORDS ***
//
Lstring LSTRING_ = { 0, L"" };
Lstring LSTRING_source = { 6, L"source" };
Lstring LSTRING_global = { 6, L"global" };
Lstring LSTRING_ignoreCase = { 10, L"ignoreCase" };
Lstring LSTRING_multiline = { 9, L"multiline" };
Lstring LSTRING_lastIndex = { 9, L"lastIndex" };
Lstring LSTRING_input = { 5, L"input" };
Lstring LSTRING_lastMatch = { 9, L"lastMatch" };
Lstring LSTRING_lastParen = { 9, L"lastParen" };
Lstring LSTRING_leftContext = { 11, L"leftContext" };
Lstring LSTRING_rightContext = { 12, L"rightContext" };
Lstring LSTRING_prototype = { 9, L"prototype" };
Lstring LSTRING_constructor = { 11, L"constructor" };
Lstring LSTRING_toString = { 8, L"toString" };
Lstring LSTRING_toLocaleString = { 14, L"toLocaleString" };
Lstring LSTRING_toSource = { 8, L"toSource" };
Lstring LSTRING_valueOf = { 7, L"valueOf" };
Lstring LSTRING_message = { 7, L"message" };
Lstring LSTRING_description = { 11, L"description" };
Lstring LSTRING_Error = { 5, L"Error" };
Lstring LSTRING_name = { 4, L"name" };
Lstring LSTRING_length = { 6, L"length" };
Lstring LSTRING_NaN = { 3, L"NaN" };
Lstring LSTRING_Infinity = { 8, L"Infinity" };
Lstring LSTRING_negInfinity = { 9, L"-Infinity" };
Lstring LSTRING_bobjectb = { 8, L"[object]" };
Lstring LSTRING_undefined = { 9, L"undefined" };
Lstring LSTRING_null = { 4, L"null" };
Lstring LSTRING_true = { 4, L"true" };
Lstring LSTRING_false = { 5, L"false" };
Lstring LSTRING_object = { 6, L"object" };
Lstring LSTRING_string = { 6, L"string" };
Lstring LSTRING_number = { 6, L"number" };
Lstring LSTRING_boolean = { 7, L"boolean" };
Lstring LSTRING_Object = { 6, L"Object" };
Lstring LSTRING_String = { 6, L"String" };
Lstring LSTRING_Number = { 6, L"Number" };
Lstring LSTRING_Boolean = { 7, L"Boolean" };
Lstring LSTRING_Date = { 4, L"Date" };
Lstring LSTRING_Array = { 5, L"Array" };
Lstring LSTRING_RegExp = { 6, L"RegExp" };
Lstring LSTRING_arity = { 5, L"arity" };
Lstring LSTRING_arguments = { 9, L"arguments" };
Lstring LSTRING_callee = { 6, L"callee" };
Lstring LSTRING_caller = { 6, L"caller" };
Lstring LSTRING_EvalError = { 9, L"EvalError" };
Lstring LSTRING_RangeError = { 10, L"RangeError" };
Lstring LSTRING_ReferenceError = { 14, L"ReferenceError" };
Lstring LSTRING_SyntaxError = { 11, L"SyntaxError" };
Lstring LSTRING_TypeError = { 9, L"TypeError" };
Lstring LSTRING_URIError = { 8, L"URIError" };
Lstring LSTRING_this = { 4, L"this" };
Lstring LSTRING_fromCharCode = { 12, L"fromCharCode" };
Lstring LSTRING_charAt = { 6, L"charAt" };
Lstring LSTRING_charCodeAt = { 10, L"charCodeAt" };
Lstring LSTRING_concat = { 6, L"concat" };
Lstring LSTRING_indexOf = { 7, L"indexOf" };
Lstring LSTRING_lastIndexOf = { 11, L"lastIndexOf" };
Lstring LSTRING_localeCompare = { 13, L"localeCompare" };
Lstring LSTRING_match = { 5, L"match" };
Lstring LSTRING_replace = { 7, L"replace" };
Lstring LSTRING_search = { 6, L"search" };
Lstring LSTRING_slice = { 5, L"slice" };
Lstring LSTRING_split = { 5, L"split" };
Lstring LSTRING_substr = { 6, L"substr" };
Lstring LSTRING_substring = { 9, L"substring" };
Lstring LSTRING_toLowerCase = { 11, L"toLowerCase" };
Lstring LSTRING_toLocaleLowerCase = { 17, L"toLocaleLowerCase" };
Lstring LSTRING_toUpperCase = { 11, L"toUpperCase" };
Lstring LSTRING_toLocaleUpperCase = { 17, L"toLocaleUpperCase" };
Lstring LSTRING_hasOwnProperty = { 14, L"hasOwnProperty" };
Lstring LSTRING_isPrototypeOf = { 13, L"isPrototypeOf" };
Lstring LSTRING_propertyIsEnumerable = { 20, L"propertyIsEnumerable" };
Lstring LSTRING_dollar1 = { 2, L"$1" };
Lstring LSTRING_dollar2 = { 2, L"$2" };
Lstring LSTRING_dollar3 = { 2, L"$3" };
Lstring LSTRING_dollar4 = { 2, L"$4" };
Lstring LSTRING_dollar5 = { 2, L"$5" };
Lstring LSTRING_dollar6 = { 2, L"$6" };
Lstring LSTRING_dollar7 = { 2, L"$7" };
Lstring LSTRING_dollar8 = { 2, L"$8" };
Lstring LSTRING_dollar9 = { 2, L"$9" };
Lstring LSTRING_index = { 5, L"index" };
Lstring LSTRING_compile = { 7, L"compile" };
Lstring LSTRING_test = { 4, L"test" };
Lstring LSTRING_exec = { 4, L"exec" };
Lstring LSTRING_MAX_VALUE = { 9, L"MAX_VALUE" };
Lstring LSTRING_MIN_VALUE = { 9, L"MIN_VALUE" };
Lstring LSTRING_NEGATIVE_INFINITY = { 17, L"NEGATIVE_INFINITY" };
Lstring LSTRING_POSITIVE_INFINITY = { 17, L"POSITIVE_INFINITY" };
Lstring LSTRING_dash = { 1, L"-" };
Lstring LSTRING_toFixed = { 7, L"toFixed" };
Lstring LSTRING_toExponential = { 13, L"toExponential" };
Lstring LSTRING_toPrecision = { 11, L"toPrecision" };
Lstring LSTRING_abs = { 3, L"abs" };
Lstring LSTRING_acos = { 4, L"acos" };
Lstring LSTRING_asin = { 4, L"asin" };
Lstring LSTRING_atan = { 4, L"atan" };
Lstring LSTRING_atan2 = { 5, L"atan2" };
Lstring LSTRING_ceil = { 4, L"ceil" };
Lstring LSTRING_cos = { 3, L"cos" };
Lstring LSTRING_exp = { 3, L"exp" };
Lstring LSTRING_floor = { 5, L"floor" };
Lstring LSTRING_log = { 3, L"log" };
Lstring LSTRING_max = { 3, L"max" };
Lstring LSTRING_min = { 3, L"min" };
Lstring LSTRING_pow = { 3, L"pow" };
Lstring LSTRING_random = { 6, L"random" };
Lstring LSTRING_round = { 5, L"round" };
Lstring LSTRING_sin = { 3, L"sin" };
Lstring LSTRING_sqrt = { 4, L"sqrt" };
Lstring LSTRING_tan = { 3, L"tan" };
Lstring LSTRING_E = { 1, L"E" };
Lstring LSTRING_LN10 = { 4, L"LN10" };
Lstring LSTRING_LN2 = { 3, L"LN2" };
Lstring LSTRING_LOG2E = { 5, L"LOG2E" };
Lstring LSTRING_LOG10E = { 6, L"LOG10E" };
Lstring LSTRING_PI = { 2, L"PI" };
Lstring LSTRING_SQRT1_2 = { 7, L"SQRT1_2" };
Lstring LSTRING_SQRT2 = { 5, L"SQRT2" };
Lstring LSTRING_parse = { 5, L"parse" };
Lstring LSTRING_UTC = { 3, L"UTC" };
Lstring LSTRING_getTime = { 7, L"getTime" };
Lstring LSTRING_getYear = { 7, L"getYear" };
Lstring LSTRING_getFullYear = { 11, L"getFullYear" };
Lstring LSTRING_getUTCFullYear = { 14, L"getUTCFullYear" };
Lstring LSTRING_getDate = { 7, L"getDate" };
Lstring LSTRING_getUTCDate = { 10, L"getUTCDate" };
Lstring LSTRING_getMonth = { 8, L"getMonth" };
Lstring LSTRING_getUTCMonth = { 11, L"getUTCMonth" };
Lstring LSTRING_getDay = { 6, L"getDay" };
Lstring LSTRING_getUTCDay = { 9, L"getUTCDay" };
Lstring LSTRING_getHours = { 8, L"getHours" };
Lstring LSTRING_getUTCHours = { 11, L"getUTCHours" };
Lstring LSTRING_getMinutes = { 10, L"getMinutes" };
Lstring LSTRING_getUTCMinutes = { 13, L"getUTCMinutes" };
Lstring LSTRING_getSeconds = { 10, L"getSeconds" };
Lstring LSTRING_getUTCSeconds = { 13, L"getUTCSeconds" };
Lstring LSTRING_getMilliseconds = { 15, L"getMilliseconds" };
Lstring LSTRING_getUTCMilliseconds = { 18, L"getUTCMilliseconds" };
Lstring LSTRING_getTimezoneOffset = { 17, L"getTimezoneOffset" };
Lstring LSTRING_getVarDate = { 10, L"getVarDate" };
Lstring LSTRING_setTime = { 7, L"setTime" };
Lstring LSTRING_setYear = { 7, L"setYear" };
Lstring LSTRING_setFullYear = { 11, L"setFullYear" };
Lstring LSTRING_setUTCFullYear = { 14, L"setUTCFullYear" };
Lstring LSTRING_setDate = { 7, L"setDate" };
Lstring LSTRING_setUTCDate = { 10, L"setUTCDate" };
Lstring LSTRING_setMonth = { 8, L"setMonth" };
Lstring LSTRING_setUTCMonth = { 11, L"setUTCMonth" };
Lstring LSTRING_setDay = { 6, L"setDay" };
Lstring LSTRING_setUTCDay = { 9, L"setUTCDay" };
Lstring LSTRING_setHours = { 8, L"setHours" };
Lstring LSTRING_setUTCHours = { 11, L"setUTCHours" };
Lstring LSTRING_setMinutes = { 10, L"setMinutes" };
Lstring LSTRING_setUTCMinutes = { 13, L"setUTCMinutes" };
Lstring LSTRING_setSeconds = { 10, L"setSeconds" };
Lstring LSTRING_setUTCSeconds = { 13, L"setUTCSeconds" };
Lstring LSTRING_setMilliseconds = { 15, L"setMilliseconds" };
Lstring LSTRING_setUTCMilliseconds = { 18, L"setUTCMilliseconds" };
Lstring LSTRING_toDateString = { 12, L"toDateString" };
Lstring LSTRING_toTimeString = { 12, L"toTimeString" };
Lstring LSTRING_toLocaleDateString = { 18, L"toLocaleDateString" };
Lstring LSTRING_toLocaleTimeString = { 18, L"toLocaleTimeString" };
Lstring LSTRING_toUTCString = { 11, L"toUTCString" };
Lstring LSTRING_toGMTString = { 11, L"toGMTString" };
Lstring LSTRING_comma = { 1, L"," };
Lstring LSTRING_join = { 4, L"join" };
Lstring LSTRING_pop = { 3, L"pop" };
Lstring LSTRING_push = { 4, L"push" };
Lstring LSTRING_reverse = { 7, L"reverse" };
Lstring LSTRING_shift = { 5, L"shift" };
Lstring LSTRING_sort = { 4, L"sort" };
Lstring LSTRING_splice = { 6, L"splice" };
Lstring LSTRING_unshift = { 7, L"unshift" };
Lstring LSTRING_apply = { 5, L"apply" };
Lstring LSTRING_call = { 4, L"call" };
Lstring LSTRING_function = { 8, L"function" };
Lstring LSTRING_eval = { 4, L"eval" };
Lstring LSTRING_parseInt = { 8, L"parseInt" };
Lstring LSTRING_parseFloat = { 10, L"parseFloat" };
Lstring LSTRING_escape = { 6, L"escape" };
Lstring LSTRING_unescape = { 8, L"unescape" };
Lstring LSTRING_isNaN = { 5, L"isNaN" };
Lstring LSTRING_isFinite = { 8, L"isFinite" };
Lstring LSTRING_decodeURI = { 9, L"decodeURI" };
Lstring LSTRING_decodeURIComponent = { 18, L"decodeURIComponent" };
Lstring LSTRING_encodeURI = { 9, L"encodeURI" };
Lstring LSTRING_encodeURIComponent = { 18, L"encodeURIComponent" };
Lstring LSTRING_print = { 5, L"print" };
Lstring LSTRING_println = { 7, L"println" };
Lstring LSTRING_readln = { 6, L"readln" };
Lstring LSTRING_getenv = { 6, L"getenv" };
Lstring LSTRING_assert = { 6, L"assert" };
Lstring LSTRING_Function = { 8, L"Function" };
Lstring LSTRING_Math = { 4, L"Math" };
Lstring LSTRING_ActiveXObject = { 13, L"ActiveXObject" };
Lstring LSTRING_GetObject = { 9, L"GetObject" };
Lstring LSTRING_0 = { 1, L"0" };
Lstring LSTRING_1 = { 1, L"1" };
Lstring LSTRING_2 = { 1, L"2" };
Lstring LSTRING_3 = { 1, L"3" };
Lstring LSTRING_4 = { 1, L"4" };
Lstring LSTRING_5 = { 1, L"5" };
Lstring LSTRING_6 = { 1, L"6" };
Lstring LSTRING_7 = { 1, L"7" };
Lstring LSTRING_8 = { 1, L"8" };
Lstring LSTRING_9 = { 1, L"9" };
Lstring LSTRING_anchor = { 6, L"anchor" };
Lstring LSTRING_big = { 3, L"big" };
Lstring LSTRING_blink = { 5, L"blink" };
Lstring LSTRING_bold = { 4, L"bold" };
Lstring LSTRING_fixed = { 5, L"fixed" };
Lstring LSTRING_fontcolor = { 9, L"fontcolor" };
Lstring LSTRING_fontsize = { 8, L"fontsize" };
Lstring LSTRING_italics = { 7, L"italics" };
Lstring LSTRING_link = { 4, L"link" };
Lstring LSTRING_small = { 5, L"small" };
Lstring LSTRING_strike = { 6, L"strike" };
Lstring LSTRING_sub = { 3, L"sub" };
Lstring LSTRING_sup = { 3, L"sup" };
Lstring LSTRING_Enumerator = { 10, L"Enumerator" };
Lstring LSTRING_item = { 4, L"item" };
Lstring LSTRING_atEnd = { 5, L"atEnd" };
Lstring LSTRING_moveNext = { 8, L"moveNext" };
Lstring LSTRING_moveFirst = { 9, L"moveFirst" };
Lstring LSTRING_VBArray = { 7, L"VBArray" };
Lstring LSTRING_dimensions = { 10, L"dimensions" };
Lstring LSTRING_getItem = { 7, L"getItem" };
Lstring LSTRING_lbound = { 6, L"lbound" };
Lstring LSTRING_toArray = { 7, L"toArray" };
Lstring LSTRING_ubound = { 6, L"ubound" };
Lstring LSTRING_ScriptEngine = { 12, L"ScriptEngine" };
Lstring LSTRING_ScriptEngineBuildVersion = { 24, L"ScriptEngineBuildVersion" };
Lstring LSTRING_ScriptEngineMajorVersion = { 24, L"ScriptEngineMajorVersion" };
Lstring LSTRING_ScriptEngineMinorVersion = { 24, L"ScriptEngineMinorVersion" };
Lstring LSTRING_CHROMEscript = { 9, L"DMDScript" };
Lstring LSTRING_date = { 4, L"date" };
Lstring LSTRING_unknown = { 7, L"unknown" };
d_string TEXT_ = &LSTRING_;
d_string TEXT_source = &LSTRING_source;
d_string TEXT_global = &LSTRING_global;
d_string TEXT_ignoreCase = &LSTRING_ignoreCase;
d_string TEXT_multiline = &LSTRING_multiline;
d_string TEXT_lastIndex = &LSTRING_lastIndex;
d_string TEXT_input = &LSTRING_input;
d_string TEXT_lastMatch = &LSTRING_lastMatch;
d_string TEXT_lastParen = &LSTRING_lastParen;
d_string TEXT_leftContext = &LSTRING_leftContext;
d_string TEXT_rightContext = &LSTRING_rightContext;
d_string TEXT_prototype = &LSTRING_prototype;
d_string TEXT_constructor = &LSTRING_constructor;
d_string TEXT_toString = &LSTRING_toString;
d_string TEXT_toLocaleString = &LSTRING_toLocaleString;
d_string TEXT_toSource = &LSTRING_toSource;
d_string TEXT_valueOf = &LSTRING_valueOf;
d_string TEXT_message = &LSTRING_message;
d_string TEXT_description = &LSTRING_description;
d_string TEXT_Error = &LSTRING_Error;
d_string TEXT_name = &LSTRING_name;
d_string TEXT_length = &LSTRING_length;
d_string TEXT_NaN = &LSTRING_NaN;
d_string TEXT_Infinity = &LSTRING_Infinity;
d_string TEXT_negInfinity = &LSTRING_negInfinity;
d_string TEXT_bobjectb = &LSTRING_bobjectb;
d_string TEXT_undefined = &LSTRING_undefined;
d_string TEXT_null = &LSTRING_null;
d_string TEXT_true = &LSTRING_true;
d_string TEXT_false = &LSTRING_false;
d_string TEXT_object = &LSTRING_object;
d_string TEXT_string = &LSTRING_string;
d_string TEXT_number = &LSTRING_number;
d_string TEXT_boolean = &LSTRING_boolean;
d_string TEXT_Object = &LSTRING_Object;
d_string TEXT_String = &LSTRING_String;
d_string TEXT_Number = &LSTRING_Number;
d_string TEXT_Boolean = &LSTRING_Boolean;
d_string TEXT_Date = &LSTRING_Date;
d_string TEXT_Array = &LSTRING_Array;
d_string TEXT_RegExp = &LSTRING_RegExp;
d_string TEXT_arity = &LSTRING_arity;
d_string TEXT_arguments = &LSTRING_arguments;
d_string TEXT_callee = &LSTRING_callee;
d_string TEXT_caller = &LSTRING_caller;
d_string TEXT_EvalError = &LSTRING_EvalError;
d_string TEXT_RangeError = &LSTRING_RangeError;
d_string TEXT_ReferenceError = &LSTRING_ReferenceError;
d_string TEXT_SyntaxError = &LSTRING_SyntaxError;
d_string TEXT_TypeError = &LSTRING_TypeError;
d_string TEXT_URIError = &LSTRING_URIError;
d_string TEXT_this = &LSTRING_this;
d_string TEXT_fromCharCode = &LSTRING_fromCharCode;
d_string TEXT_charAt = &LSTRING_charAt;
d_string TEXT_charCodeAt = &LSTRING_charCodeAt;
d_string TEXT_concat = &LSTRING_concat;
d_string TEXT_indexOf = &LSTRING_indexOf;
d_string TEXT_lastIndexOf = &LSTRING_lastIndexOf;
d_string TEXT_localeCompare = &LSTRING_localeCompare;
d_string TEXT_match = &LSTRING_match;
d_string TEXT_replace = &LSTRING_replace;
d_string TEXT_search = &LSTRING_search;
d_string TEXT_slice = &LSTRING_slice;
d_string TEXT_split = &LSTRING_split;
d_string TEXT_substr = &LSTRING_substr;
d_string TEXT_substring = &LSTRING_substring;
d_string TEXT_toLowerCase = &LSTRING_toLowerCase;
d_string TEXT_toLocaleLowerCase = &LSTRING_toLocaleLowerCase;
d_string TEXT_toUpperCase = &LSTRING_toUpperCase;
d_string TEXT_toLocaleUpperCase = &LSTRING_toLocaleUpperCase;
d_string TEXT_hasOwnProperty = &LSTRING_hasOwnProperty;
d_string TEXT_isPrototypeOf = &LSTRING_isPrototypeOf;
d_string TEXT_propertyIsEnumerable = &LSTRING_propertyIsEnumerable;
d_string TEXT_dollar1 = &LSTRING_dollar1;
d_string TEXT_dollar2 = &LSTRING_dollar2;
d_string TEXT_dollar3 = &LSTRING_dollar3;
d_string TEXT_dollar4 = &LSTRING_dollar4;
d_string TEXT_dollar5 = &LSTRING_dollar5;
d_string TEXT_dollar6 = &LSTRING_dollar6;
d_string TEXT_dollar7 = &LSTRING_dollar7;
d_string TEXT_dollar8 = &LSTRING_dollar8;
d_string TEXT_dollar9 = &LSTRING_dollar9;
d_string TEXT_index = &LSTRING_index;
d_string TEXT_compile = &LSTRING_compile;
d_string TEXT_test = &LSTRING_test;
d_string TEXT_exec = &LSTRING_exec;
d_string TEXT_MAX_VALUE = &LSTRING_MAX_VALUE;
d_string TEXT_MIN_VALUE = &LSTRING_MIN_VALUE;
d_string TEXT_NEGATIVE_INFINITY = &LSTRING_NEGATIVE_INFINITY;
d_string TEXT_POSITIVE_INFINITY = &LSTRING_POSITIVE_INFINITY;
d_string TEXT_dash = &LSTRING_dash;
d_string TEXT_toFixed = &LSTRING_toFixed;
d_string TEXT_toExponential = &LSTRING_toExponential;
d_string TEXT_toPrecision = &LSTRING_toPrecision;
d_string TEXT_abs = &LSTRING_abs;
d_string TEXT_acos = &LSTRING_acos;
d_string TEXT_asin = &LSTRING_asin;
d_string TEXT_atan = &LSTRING_atan;
d_string TEXT_atan2 = &LSTRING_atan2;
d_string TEXT_ceil = &LSTRING_ceil;
d_string TEXT_cos = &LSTRING_cos;
d_string TEXT_exp = &LSTRING_exp;
d_string TEXT_floor = &LSTRING_floor;
d_string TEXT_log = &LSTRING_log;
d_string TEXT_max = &LSTRING_max;
d_string TEXT_min = &LSTRING_min;
d_string TEXT_pow = &LSTRING_pow;
d_string TEXT_random = &LSTRING_random;
d_string TEXT_round = &LSTRING_round;
d_string TEXT_sin = &LSTRING_sin;
d_string TEXT_sqrt = &LSTRING_sqrt;
d_string TEXT_tan = &LSTRING_tan;
d_string TEXT_E = &LSTRING_E;
d_string TEXT_LN10 = &LSTRING_LN10;
d_string TEXT_LN2 = &LSTRING_LN2;
d_string TEXT_LOG2E = &LSTRING_LOG2E;
d_string TEXT_LOG10E = &LSTRING_LOG10E;
d_string TEXT_PI = &LSTRING_PI;
d_string TEXT_SQRT1_2 = &LSTRING_SQRT1_2;
d_string TEXT_SQRT2 = &LSTRING_SQRT2;
d_string TEXT_parse = &LSTRING_parse;
d_string TEXT_UTC = &LSTRING_UTC;
d_string TEXT_getTime = &LSTRING_getTime;
d_string TEXT_getYear = &LSTRING_getYear;
d_string TEXT_getFullYear = &LSTRING_getFullYear;
d_string TEXT_getUTCFullYear = &LSTRING_getUTCFullYear;
d_string TEXT_getDate = &LSTRING_getDate;
d_string TEXT_getUTCDate = &LSTRING_getUTCDate;
d_string TEXT_getMonth = &LSTRING_getMonth;
d_string TEXT_getUTCMonth = &LSTRING_getUTCMonth;
d_string TEXT_getDay = &LSTRING_getDay;
d_string TEXT_getUTCDay = &LSTRING_getUTCDay;
d_string TEXT_getHours = &LSTRING_getHours;
d_string TEXT_getUTCHours = &LSTRING_getUTCHours;
d_string TEXT_getMinutes = &LSTRING_getMinutes;
d_string TEXT_getUTCMinutes = &LSTRING_getUTCMinutes;
d_string TEXT_getSeconds = &LSTRING_getSeconds;
d_string TEXT_getUTCSeconds = &LSTRING_getUTCSeconds;
d_string TEXT_getMilliseconds = &LSTRING_getMilliseconds;
d_string TEXT_getUTCMilliseconds = &LSTRING_getUTCMilliseconds;
d_string TEXT_getTimezoneOffset = &LSTRING_getTimezoneOffset;
d_string TEXT_getVarDate = &LSTRING_getVarDate;
d_string TEXT_setTime = &LSTRING_setTime;
d_string TEXT_setYear = &LSTRING_setYear;
d_string TEXT_setFullYear = &LSTRING_setFullYear;
d_string TEXT_setUTCFullYear = &LSTRING_setUTCFullYear;
d_string TEXT_setDate = &LSTRING_setDate;
d_string TEXT_setUTCDate = &LSTRING_setUTCDate;
d_string TEXT_setMonth = &LSTRING_setMonth;
d_string TEXT_setUTCMonth = &LSTRING_setUTCMonth;
d_string TEXT_setDay = &LSTRING_setDay;
d_string TEXT_setUTCDay = &LSTRING_setUTCDay;
d_string TEXT_setHours = &LSTRING_setHours;
d_string TEXT_setUTCHours = &LSTRING_setUTCHours;
d_string TEXT_setMinutes = &LSTRING_setMinutes;
d_string TEXT_setUTCMinutes = &LSTRING_setUTCMinutes;
d_string TEXT_setSeconds = &LSTRING_setSeconds;
d_string TEXT_setUTCSeconds = &LSTRING_setUTCSeconds;
d_string TEXT_setMilliseconds = &LSTRING_setMilliseconds;
d_string TEXT_setUTCMilliseconds = &LSTRING_setUTCMilliseconds;
d_string TEXT_toDateString = &LSTRING_toDateString;
d_string TEXT_toTimeString = &LSTRING_toTimeString;
d_string TEXT_toLocaleDateString = &LSTRING_toLocaleDateString;
d_string TEXT_toLocaleTimeString = &LSTRING_toLocaleTimeString;
d_string TEXT_toUTCString = &LSTRING_toUTCString;
d_string TEXT_toGMTString = &LSTRING_toGMTString;
d_string TEXT_comma = &LSTRING_comma;
d_string TEXT_join = &LSTRING_join;
d_string TEXT_pop = &LSTRING_pop;
d_string TEXT_push = &LSTRING_push;
d_string TEXT_reverse = &LSTRING_reverse;
d_string TEXT_shift = &LSTRING_shift;
d_string TEXT_sort = &LSTRING_sort;
d_string TEXT_splice = &LSTRING_splice;
d_string TEXT_unshift = &LSTRING_unshift;
d_string TEXT_apply = &LSTRING_apply;
d_string TEXT_call = &LSTRING_call;
d_string TEXT_function = &LSTRING_function;
d_string TEXT_eval = &LSTRING_eval;
d_string TEXT_parseInt = &LSTRING_parseInt;
d_string TEXT_parseFloat = &LSTRING_parseFloat;
d_string TEXT_escape = &LSTRING_escape;
d_string TEXT_unescape = &LSTRING_unescape;
d_string TEXT_isNaN = &LSTRING_isNaN;
d_string TEXT_isFinite = &LSTRING_isFinite;
d_string TEXT_decodeURI = &LSTRING_decodeURI;
d_string TEXT_decodeURIComponent = &LSTRING_decodeURIComponent;
d_string TEXT_encodeURI = &LSTRING_encodeURI;
d_string TEXT_encodeURIComponent = &LSTRING_encodeURIComponent;
d_string TEXT_print = &LSTRING_print;
d_string TEXT_println = &LSTRING_println;
d_string TEXT_readln = &LSTRING_readln;
d_string TEXT_getenv = &LSTRING_getenv;
d_string TEXT_assert = &LSTRING_assert;
d_string TEXT_Function = &LSTRING_Function;
d_string TEXT_Math = &LSTRING_Math;
d_string TEXT_ActiveXObject = &LSTRING_ActiveXObject;
d_string TEXT_GetObject = &LSTRING_GetObject;
d_string TEXT_0 = &LSTRING_0;
d_string TEXT_1 = &LSTRING_1;
d_string TEXT_2 = &LSTRING_2;
d_string TEXT_3 = &LSTRING_3;
d_string TEXT_4 = &LSTRING_4;
d_string TEXT_5 = &LSTRING_5;
d_string TEXT_6 = &LSTRING_6;
d_string TEXT_7 = &LSTRING_7;
d_string TEXT_8 = &LSTRING_8;
d_string TEXT_9 = &LSTRING_9;
d_string TEXT_anchor = &LSTRING_anchor;
d_string TEXT_big = &LSTRING_big;
d_string TEXT_blink = &LSTRING_blink;
d_string TEXT_bold = &LSTRING_bold;
d_string TEXT_fixed = &LSTRING_fixed;
d_string TEXT_fontcolor = &LSTRING_fontcolor;
d_string TEXT_fontsize = &LSTRING_fontsize;
d_string TEXT_italics = &LSTRING_italics;
d_string TEXT_link = &LSTRING_link;
d_string TEXT_small = &LSTRING_small;
d_string TEXT_strike = &LSTRING_strike;
d_string TEXT_sub = &LSTRING_sub;
d_string TEXT_sup = &LSTRING_sup;
d_string TEXT_Enumerator = &LSTRING_Enumerator;
d_string TEXT_item = &LSTRING_item;
d_string TEXT_atEnd = &LSTRING_atEnd;
d_string TEXT_moveNext = &LSTRING_moveNext;
d_string TEXT_moveFirst = &LSTRING_moveFirst;
d_string TEXT_VBArray = &LSTRING_VBArray;
d_string TEXT_dimensions = &LSTRING_dimensions;
d_string TEXT_getItem = &LSTRING_getItem;
d_string TEXT_lbound = &LSTRING_lbound;
d_string TEXT_toArray = &LSTRING_toArray;
d_string TEXT_ubound = &LSTRING_ubound;
d_string TEXT_ScriptEngine = &LSTRING_ScriptEngine;
d_string TEXT_ScriptEngineBuildVersion = &LSTRING_ScriptEngineBuildVersion;
d_string TEXT_ScriptEngineMajorVersion = &LSTRING_ScriptEngineMajorVersion;
d_string TEXT_ScriptEngineMinorVersion = &LSTRING_ScriptEngineMinorVersion;
d_string TEXT_CHROMEscript = &LSTRING_CHROMEscript;
d_string TEXT_date = &LSTRING_date;
d_string TEXT_unknown = &LSTRING_unknown;
//
// *** ERROR MESSAGES ***
//
char * errmsgtbl[] = {
	"DMDScript fatal runtime error: ",
	"No default value for COM object",
	"%s does not have a [[Construct]] property",
	"argument type mismatch for %s",
	"wrong number of arguments for %s",
	"%s Invoke() fails with COM error %x",
	"Dcomobject: %s.%s fails with COM error %x",
	"unrecognized switch '%s'",
	"undefined label '%s' in function '%s'",
	"unterminated /* */ comment",
	"<!-- comment does not end in newline",
	"unsupported char '%c'",
	"unsupported char 0x%02x",
	"escape hex sequence requires 2 hex digits",
	"undefined escape sequence \\%c",
	"string is missing an end quote",
	"end of file before end of string",
	"\\u sequence must be followed by 4 hex characters",
	"unrecognized numeric literal",
	"Identifier expected in FormalParameterList, not %s",
	"comma expected in FormalParameterList, not %s",
	"identifier expected",
	"found '%s' when expecting '%s'",
	"identifier expected instead of '%s'",
	"identifier expected following '%s', not '%s'",
	"EOF found before closing '}' of block statement",
	"only one variable can be declared for 'in', not %d",
	"';' or 'in' expected, not '%s'",
	"label expected after goto, not '%s'",
	"catch or finally expected following try",
	"found '%s' instead of statement",
	"expression expected, not '%s'",
	"Object literal in initializer",
	"label '%s' is already defined",
	"redundant case %s",
	"case %s: is not in a switch statement",
	"redundant default in switch statement",
	"default is not in a switch statement",
	"init statement must be expression or var",
	"can only break from within loop or switch",
	"continue is not in a loop",
	"Statement label '%s' is undefined",
	"cannot goto into with statement",
	"can only return from within function",
	"no expression for throw",
	"'%s' has no semantic routine",
	"%s.%s is undefined",
	"Symbol %s.%s is already defined",
	"%s.%s expects a Number not a %s",
	"%s.%s expects a String not a %s",
	"%s.%s expects a Date not a %s",
	"%s %s is undefined and has no Call method",
	"%s %s.%s is undefined and has no Call method",
	"%s.%s expects a Boolean not a %s",
	"arg to Array(len) must be 0 .. 2**32-1, not %.16g",
	"%s %s out of range",
	"TypeError in %s",
	"Error compiling regular expression",
	"%s not transferrable",
	"%s %s cannot convert to Object",
	"%s %s.%s cannot convert to Object",
	"cannot convert %s to Object",
	"cannot assign to %s",
	"cannot assign %s to %s",
	"cannot assign to %s.%s",
	"cannot assign to function",
	"RHS of %s must be an Object, not a %s",
	"can't Put('%s', %s) to a primitive %s",
	"can't Put(%u, %s) to a primitive %s",
	"object cannot be converted to a primitive type",
	"can't Get(%s) from primitive %s(%s)",
	"can't Get(%d) from primitive %s(%s)",
	"primitive %s has no Construct method",
	"primitive %s has no Call method",
	"for-in must be on an object, not a primitive",
	"assert() line %d",
	"object does not have a [[Call]] property",
	"%s: %s",
	"no Default Put for object",
	"%s does not have a [[Construct]] property",
	"%s does not have a [[Call]] property",
	"%s does not have a [[HasInstance]] property",
	"length property must be an integer",
	"Array.prototype.toLocaleString() not transferrable",
	"Function.prototype.toString() not transferrable",
	"Function.prototype.apply(): argArray must be array or arguments object",
	".prototype must be an Object, not a %s",
	"VBArray expected, not a %s",
	"VBArray subscript out of range",
	"Type mismatch",
	"no property %s",
	"Put of %s failed",
	"Get of %s failed",
	"argument not a collection",
	"Unexpected",
};
unsigned short errcodtbl[] = {
	0u,
	0u,
	445u,
	13u,
	450u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	1002u,
	1010u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	1019u,
	1020u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	5001u,
	5005u,
	5006u,
	5007u,
	5007u,
	5010u,
	5029u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	5007u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	5100u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	0u,
	5u,
	0u,
	0u,
	0u,
};
